//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDisableKey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResRegister {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResRegister() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDisableKey.ResRegister", typeof(ResRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a trial version of the application. Press the &quot;Buy now&quot; button to buy a license..
        /// </summary>
        internal static string Add_new_search_item_to_project {
            get {
                return ResourceManager.GetString("Add new search item to project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful! Please restart the application..
        /// </summary>
        internal static string Continue_activated_search_ {
            get {
                return ResourceManager.GetString("Continue activated search?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Registration ! Please contact the author of the application..
        /// </summary>
        internal static string Direct_search_started {
            get {
                return ResourceManager.GetString("Direct search started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test period of the application has expired. Press the &quot;Buy now&quot; button to buy a license..
        /// </summary>
        internal static string Edit_4dots_Project {
            get {
                return ResourceManager.GetString("Edit 4dots Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Unable to register. Please contact the author of the application if this error persists..
        /// </summary>
        internal static string Erroneous_search_2 {
            get {
                return ResourceManager.GetString("Erroneous search 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 1.
        /// </summary>
        internal static string Error_1 {
            get {
                return ResourceManager.GetString("Error 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        internal static string Error_12 {
            get {
                return ResourceManager.GetString("Error 12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 4.
        /// </summary>
        internal static string Error_4 {
            get {
                return ResourceManager.GetString("Error 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2as212e12.
        /// </summary>
        internal static string Import_search_result {
            get {
                return ResourceManager.GetString("Import search result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsTrd.
        /// </summary>
        internal static string Init_Project {
            get {
                return ResourceManager.GetString("Init Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle7.
        /// </summary>
        internal static string MessageTitle7 {
            get {
                return ResourceManager.GetString("MessageTitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle8.
        /// </summary>
        internal static string MessageTitle8 {
            get {
                return ResourceManager.GetString("MessageTitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID REGISTRATION.
        /// </summary>
        internal static string Search_duration_process {
            get {
                return ResourceManager.GetString("Search duration process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        internal static string Uniform_process {
            get {
                return ResourceManager.GetString("Uniform process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Disable Key.
        /// </summary>
        internal static string Αλλαγή_Ονόματος {
            get {
                return ResourceManager.GetString("Αλλαγή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string Αλλαγή_στοιχείων_εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή στοιχείων εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 435HTrRR.
        /// </summary>
        internal static string Αλλαγή_Φίλτρου_Εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή Φίλτρου Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?optionfile=.
        /// </summary>
        internal static string Ανανέωση_Εικόνας {
            get {
                return ResourceManager.GetString("Ανανέωση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23t44des.
        /// </summary>
        internal static string Εισαγωγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εισαγωγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tas151e8.
        /// </summary>
        internal static string Εναλλαγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εναλλαγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||***DTT***|||.
        /// </summary>
        internal static string Καθορισμός_Ονόματος {
            get {
                return ResourceManager.GetString("Καθορισμός Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e1h2dFfEedeeYFUrts434323.
        /// </summary>
        internal static string Μορφοποίηση_Εικόνας {
            get {
                return ResourceManager.GetString("Μορφοποίηση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Kmbrd.
        /// </summary>
        internal static string Νέα_Εικόνα {
            get {
                return ResourceManager.GetString("Νέα Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        internal static string Παράμετροι_Μετρήσεως_Εικόνας {
            get {
                return ResourceManager.GetString("Παράμετροι Μετρήσεως Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f8f8dFfYfly00eEFCdes3744.
        /// </summary>
        internal static string Περιγραφή_Ονόματος {
            get {
                return ResourceManager.GetString("Περιγραφή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||12|||.
        /// </summary>
        internal static string Πηγή_Εικόνας {
            get {
                return ResourceManager.GetString("Πηγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\.
        /// </summary>
        internal static string Προβολή_Εικόνας_1 {
            get {
                return ResourceManager.GetString("Προβολή Εικόνας 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\dbdems.dll.
        /// </summary>
        internal static string Προβολή_Εικόνων {
            get {
                return ResourceManager.GetString("Προβολή Εικόνων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4dots-software.com/registration/registernew.simple-disable-key.php.
        /// </summary>
        internal static string Σφάλμα_120 {
            get {
                return ResourceManager.GetString("Σφάλμα 120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string Σφάλμα_1201 {
            get {
                return ResourceManager.GetString("Σφάλμα 1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203023 DR-24031.
        /// </summary>
        internal static string Υπολογισμός_Επιφάνειας {
            get {
                return ResourceManager.GetString("Υπολογισμός Επιφάνειας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 145ft2fdftyef3er12zaaTGD.
        /// </summary>
        internal static string Φίλτρο_Εικόνας {
            get {
                return ResourceManager.GetString("Φίλτρο Εικόνας", resourceCulture);
            }
        }
    }
}
